[package]
name = "fuck-leetcode"
version = "0.1.0"
authors = ["cbbfcd 2890636389@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leetcode_prelude = "0.2.3"
rand = "0.6.5"
